### ISSUE TITLE
Make gobundle work with go generate

### ISSUE THREAD

**Issue by talglobus** [alecthomas/gobundle#6]
Go 1.4 introduced [`go generate`](https://blog.golang.org/generate), allowing for use of tools like `gobundle` to integrate directly into the Go build process with the addition of a single comment on the part of the user.

The process of doing so is described [here](https://golang.org/pkg/cmd/go/internal/generate/), and the Go team also recommends a short [design document](https://golang.org/s/go1.4-generate) introducing the motivations behind the tool.

**Comment by alecthomas** [comment]
I'm aware of go generate...nothing precludes using gobundle with it AFAICT.
